In [20]:
import pandas as pd
import numpy as np
import json

In [21]:
with open("data.jsonl", "r", encoding="utf-8") as file:
    data = (json.loads(line[:-1]) for line in file.readlines())

In [22]:
df = pd.json_normalize(data)

In [23]:
pd.set_option("display.max_columns", 50)

In [24]:
df = df.dropna(how="all", axis="columns")

In [25]:
df = df[[
    'nameEng',
    'hasWhatsapp',
    'primaryPhone',
    'primaryEmail',
    'primaryWebsite',
    'facebookUrl',
    'linkedInUrl',
    'twitterUrl',
    'instagramUrl',
    'poBox',
    'address',
    'categories',
]]

In [33]:
df["primaryPhone"] = df["primaryPhone"].str.replace(r"\s", "", regex=True)

In [34]:
df

,nameEng,hasWhatsapp,primaryPhone,primaryEmail,primaryWebsite,facebookUrl,linkedInUrl,twitterUrl,instagramUrl,poBox,address,categories,0,1,2
0,Flameco General Trading LLC,True,97142414494,sales@flamecogroup.net,https://www.flamecogroup.net/,https://www.facebook.com/Flamecogeneraltradingllc,https://www.linkedin.com/company/flameco-group,https://twitter.com/FlamecoGroup,https://www.instagram.com/flameco_group/,191893,OFFICE 906 | B2B TOWER | BUSINESS BAY | DUBAI-UAE,"[{'id': '674', 'nameEng': 'Construction Materi...",NaN,NaN,NaN
1,Al Donna Trading Co. (L.L.C),True,97142973123,salman305@hotmail.com,None,None,None,None,None,None,Dubai,"[{'id': '271', 'nameEng': 'Blankets , Towels &...",NaN,NaN,NaN
2,Al Banfsaj Building Material Trading,True,97142582280,info@albanfsaj.com,None,None,None,None,None,79325,"Damascus Street, Al Qusais Industrial Area, Dubai","[{'id': '2788', 'nameEng': 'Trading In Buildin...",NaN,NaN,NaN
3,AL KAMDA GENRAL TRADING L.L.C.,True,97142664200,alkamda@emirates.ae,http://www.alkamda.com,None,None,None,None,None,"Ground Floor, Gargash Building, Salahuddin Roa...","[{'id': '1315', 'nameEng': 'Gymnasium Equipmen...",NaN,NaN,NaN
4,Emirates National General Trading (LLC),True,97142221596,carsales@engt.ae,http://www.engt.ae,None,None,None,None,11745,"Floor # 2, Al Salemiyah Tower, Office # 202, ...","[{'id': '586', 'nameEng': 'Commercial Vehicles...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28695,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Agricultural Pest Control,Chemicals Trading,Commercial Agencies
28696,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chemicals Trading,Importing,Oil & Gas Installations and Fields Services
28697,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chemicals Trading,Importing,Oil & Gas Installations and Fields Services
28698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Building Materials Trading,Chemicals Trading,Heavy Equipment and Machinery Spare Parts Trading
28699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Building Materials Trading,Chemicals Trading,Electric Wiring And Accessory Trading